/*
 * Copyright (C) 2025-2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */

package mekhq.campaign.espionage;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

public class IntelEvent {

    public enum EventState {
        // Before start date
        NOT_STARTED,
        // On or after start date but before end date
        STARTED,
        // If any testFunctions have passed
        PARTIALLY_COMPLETED,
        // If end date has passed without achieving one of the completion types
        EXPIRED,
        // Completion types
        SUCCEEDED,
        FAILED,
        DRAW
    }

    private EventState state = EventState.NOT_STARTED;

    // Universal "Location" doesn't exist yet, use a List for now.
    private ArrayList<String> locationParts;
    private LocalDate startDate;
    private LocalDate endDate;
    private ArrayList<Integer> participantIds;
    private ArrayList<Integer> itemIds;

    // For display
    private String title = "";
    private String description = "";

    // This is the meat of the event handling; all of these will be generated by the EspionageFactory
    // and updated/evaluated by the EspionageManager.
    private ArrayList<IntelEventPrerequisite> prerequisites;
    private ArrayList<Supplier<Boolean>> testFunctions;
    private ArrayList<IntelOutcome> outcomes;

    public IntelEvent() {
        this(
              "",
              "",
              new ArrayList(List.of("", "", "")),
              LocalDate.now(),
              LocalDate.now().plusDays(7),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>()
        );
    }

    public IntelEvent(
          String title,
          String description,
          ArrayList<String> locationParts,
          LocalDate startDate,
          LocalDate endDate,
          ArrayList<Integer> participantIds,
          ArrayList<Integer> itemIds,
          ArrayList<IntelEventPrerequisite> prerequisites,
          ArrayList<Supplier<Boolean>> testFunctions,
          ArrayList<IntelOutcome> outcomes
    ) {
        this.locationParts = locationParts;
        this.startDate = startDate;
        this.endDate = endDate;
        this.participantIds = participantIds;
        this.itemIds = itemIds;
        this.title = title;
        this.description = description;

        this.prerequisites = prerequisites;
        this.testFunctions = testFunctions;
        this.outcomes = outcomes;
    }

    public ArrayList<String> getLocationParts() {
        return locationParts;
    }

    public void setLocationParts(ArrayList<String> locationParts) {
        this.locationParts = locationParts;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public ArrayList<Integer> getParticipantIds() {
        return participantIds;
    }

    public void setParticipantIds(ArrayList<Integer> participantIds) {
        this.participantIds = participantIds;
    }

    public ArrayList<Integer> getItemIds() {
        return itemIds;
    }

    public void setItemIds(ArrayList<Integer> itemIds) {
        this.itemIds = itemIds;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ArrayList<IntelEventPrerequisite> getPrerequisites() {
        return prerequisites;
    }

    public void setPrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        this.prerequisites = prerequisites;
    }

    public void addPrerequisite(IntelEventPrerequisite prerequisite) {
        if (prerequisites == null) {
            prerequisites = new ArrayList<>();
        }
        prerequisites.add(prerequisite);
    }

    public void addPrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        if (this.prerequisites == null) {
            this.prerequisites = new ArrayList<>();
        }
        this.prerequisites.addAll(prerequisites);
    }

    public void removePrerequisite(IntelEventPrerequisite prerequisite) {
        if (prerequisites == null) {
            return;
        }
        prerequisites.remove(prerequisite);
    }

    public void removePrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        if (this.prerequisites == null) {
            return;
        }
        this.prerequisites.removeAll(prerequisites);
    }

    public ArrayList<Supplier<Boolean>> getTestFunctions() {
        return testFunctions;
    }

    public void setTestFunctions(ArrayList<Supplier<Boolean>> testFunctions) {
        this.testFunctions = testFunctions;
    }

    public void addTestFunction(Supplier<Boolean> testFunction) {
        if (testFunctions == null) {
            testFunctions = new ArrayList<>();
        }
        testFunctions.add(testFunction);
    }

    public void addTestFunctions(ArrayList<Supplier<Boolean>> testFunctions) {
        if (this.testFunctions == null) {
            this.testFunctions = new ArrayList<>();
        }
        this.testFunctions.addAll(testFunctions);
    }

    public void removeTestFunction(Supplier<Boolean> testFunction) {
        if (testFunctions == null) {
            return;
        }
        testFunctions.remove(testFunction);
    }

    public void removeTestFunctions(ArrayList<Supplier<Boolean>> testFunctions) {
        if (this.testFunctions == null) {
            return;
        }
        this.testFunctions.removeAll(testFunctions);
    }

    public ArrayList<IntelOutcome> getOutcomes() {
        return outcomes;
    }

    public void setOutcomes(ArrayList<IntelOutcome> outcomes) {
        this.outcomes = outcomes;
    }

    public void removeOutcome(IntelOutcome outcome) {
        if (outcomes == null) {
            return;
        }
        this.outcomes.remove(outcome);
    }

    public void addOutcome(IntelOutcome outcome) {
        if (outcomes == null) {
            outcomes = new ArrayList<>();
        }
        this.outcomes.add(outcome);
    }

    public void removeOutcomes(ArrayList<IntelOutcome> outcomes) {
        if (this.outcomes == null) {
            return;
        }
        this.outcomes.removeAll(outcomes);
    }

    public void addOutcomes(ArrayList<IntelOutcome> outcomes) {
        if (this.outcomes == null) {
            this.outcomes = new ArrayList<>();
        }
        this.outcomes.addAll(outcomes);
    }

    public String update(LocalDate date) {
        StringBuilder builder = new StringBuilder();

        // Update state if necessary.
        EventState newState = switch (state) {
            case NOT_STARTED -> (date.equals(startDate) || date.isAfter(startDate)) ? EventState.STARTED : EventState.NOT_STARTED;
            case PARTIALLY_COMPLETED, STARTED -> (date.isAfter(endDate)) ? EventState.EXPIRED : EventState.STARTED;
            case EXPIRED, SUCCEEDED, FAILED, DRAW -> state;
        };

        // TODO: complete this code.

        return builder.toString();
    }

}
