/*
 * Copyright (C) 2025-2026 The MegaMek Team. All Rights Reserved.
 *
 * This file is part of MekHQ.
 *
 * MekHQ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL),
 * version 3 or (at your option) any later version,
 * as published by the Free Software Foundation.
 *
 * MekHQ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * A copy of the GPL should have been included with this project;
 * if not, see <https://www.gnu.org/licenses/>.
 *
 * NOTICE: The MegaMek organization is a non-profit group of volunteers
 * creating free software for the BattleTech community.
 *
 * MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
 * of The Topps Company, Inc. All Rights Reserved.
 *
 * Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
 * InMediaRes Productions, LLC.
 *
 * MechWarrior Copyright Microsoft Corporation. MekHQ was created under
 * Microsoft's "Game Content Usage Rules"
 * <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
 * affiliated with Microsoft.
 */

package mekhq.campaign.espionage;

import megamek.Version;
import megamek.logging.MMLogger;
import mekhq.MekHQ;
import mekhq.campaign.Campaign;
import mekhq.utilities.MHQXMLUtility;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

import java.io.PrintWriter;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.function.Supplier;

public class IntelEvent {
    protected static final MMLogger LOGGER = MMLogger.create(IntelEvent.class);

    protected static final ResourceBundle resources = ResourceBundle.getBundle(
          "mekhq.resources.Espionage",
          MekHQ.getMHQOptions().getLocale());

    public enum EventState {
        // Before start date
        NOT_STARTED,
        // On or after start date but before end date
        STARTED,
        // If any testFunctions have passed
        PARTIALLY_COMPLETED,
        // If all testFunctions have passed
        COMPLETED,
        // If end date has passed without achieving one of the completion types
        EXPIRED,
        // Completion types
        SUCCEEDED,
        FAILED,
        DRAW
    }

    private EventState state = EventState.NOT_STARTED;
    private int eventId;

    // Universal "Location" doesn't exist yet, use a List for now.
    private ArrayList<String> locationParts;
    private LocalDate startDate;
    private LocalDate endDate;
    // these IDs refer to Players/factions/forces/bot forces, not Persons.
    // Persons participating in Events will be tracked by the Manager and consumed by the Factory to add IntelOutcomes
    // affecting them individually / en masse.
    private ArrayList<Integer> participantIds;
    private ArrayList<Integer> itemIds;

    // For display
    private String title = "";
    private String description = "";

    // This is the meat of the event handling; all of these will be generated by the EspionageFactory
    // and updated/evaluated by the EspionageManager.
    private ArrayList<IntelEventPrerequisite> prerequisites;
    private ArrayList<ISerializableSupplier<Boolean>> testFunctions;
    private ArrayList<IntelOutcome> outcomes;

    public IntelEvent() {
        this(
              "",
              "",
              0,
              new ArrayList<String>(List.of("", "", "")),
              LocalDate.now(),
              LocalDate.now().plusDays(7),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>(),
              new ArrayList<>()
        );
    }

    public IntelEvent(
          String title,
          String description,
          int eventId,
          ArrayList<String> locationParts,
          LocalDate startDate,
          LocalDate endDate,
          ArrayList<Integer> participantIds,
          ArrayList<Integer> itemIds,
          ArrayList<IntelEventPrerequisite> prerequisites,
          ArrayList<ISerializableSupplier<Boolean>> testFunctions,
          ArrayList<IntelOutcome> outcomes
    ) {
        this.title = title;
        this.description = description;
        this.eventId = eventId;
        this.locationParts = locationParts;
        this.startDate = startDate;
        this.endDate = endDate;
        this.participantIds = participantIds;
        this.itemIds = itemIds;

        this.prerequisites = prerequisites;
        this.testFunctions = testFunctions;
        this.outcomes = outcomes;
    }

    // TODO: replace with ILocation / POI once merged
    public ArrayList<String> getLocationParts() {
        return locationParts;
    }

    public void setLocationParts(ArrayList<String> locationParts) {
        this.locationParts = locationParts;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public ArrayList<Integer> getParticipantIds() {
        return participantIds;
    }

    public void setParticipantIds(ArrayList<Integer> participantIds) {
        this.participantIds = participantIds;
    }

    public void addParticipantId(int id) {
        this.participantIds.add(id);
    }

    public void removeParticipantId(int id) {
        if (participantIds != null && participantIds.contains(id)) {
            participantIds.remove(id);
        }
    }

    public boolean containsParticipantId(int id) {
        return (participantIds != null) && participantIds.contains(id);
    }

    public ArrayList<Integer> getItemIds() {
        return itemIds;
    }

    public void setItemIds(ArrayList<Integer> itemIds) {
        this.itemIds = itemIds;
    }

    public void addItemId(int id) {
        this.itemIds.add(id);
    }

    public void removeItemId(int id) {
        if (itemIds != null && itemIds.contains(id)) {
            itemIds.remove(id);
        }
    }

    public boolean containsItemId(int id) {
        return (itemIds != null) && itemIds.contains(id);
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    public int getEventId() {
        return eventId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public ArrayList<IntelEventPrerequisite> getPrerequisites() {
        return prerequisites;
    }

    public void setPrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        this.prerequisites = prerequisites;
    }

    public void addPrerequisite(IntelEventPrerequisite prerequisite) {
        if (prerequisites == null) {
            prerequisites = new ArrayList<>();
        }
        prerequisites.add(prerequisite);
    }

    public void addPrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        if (this.prerequisites == null) {
            this.prerequisites = new ArrayList<>();
        }
        this.prerequisites.addAll(prerequisites);
    }

    public void removePrerequisite(IntelEventPrerequisite prerequisite) {
        if (prerequisites == null) {
            return;
        }
        prerequisites.remove(prerequisite);
    }

    public void removePrerequisites(ArrayList<IntelEventPrerequisite> prerequisites) {
        if (this.prerequisites == null) {
            return;
        }
        this.prerequisites.removeAll(prerequisites);
    }

    public ArrayList<ISerializableSupplier<Boolean>> getTestFunctions() {
        return testFunctions;
    }

    public void setTestFunctions(ArrayList<ISerializableSupplier<Boolean>> testFunctions) {
        this.testFunctions = testFunctions;
    }

    public void addTestFunction(ISerializableSupplier<Boolean> testFunction) {
        if (testFunctions == null) {
            testFunctions = new ArrayList<ISerializableSupplier<Boolean>>();
        }
        testFunctions.add(testFunction);
    }

    public void addTestFunctions(ArrayList<ISerializableSupplier<Boolean>> testFunctions) {
        if (this.testFunctions == null) {
            this.testFunctions = new ArrayList<ISerializableSupplier<Boolean>>();
        }
        this.testFunctions.addAll(testFunctions);
    }

    public void removeTestFunction(Supplier<Boolean> testFunction) {
        if (testFunctions == null) {
            return;
        }
        testFunctions.remove(testFunction);
    }

    public void removeTestFunctions(ArrayList<Supplier<Boolean>> testFunctions) {
        if (this.testFunctions == null) {
            return;
        }
        this.testFunctions.removeAll(testFunctions);
    }

    public ArrayList<IntelOutcome> getOutcomes() {
        return outcomes;
    }

    public void setOutcomes(ArrayList<IntelOutcome> outcomes) {
        this.outcomes = outcomes;
    }

    public void removeOutcome(IntelOutcome outcome) {
        if (outcomes == null) {
            return;
        }
        this.outcomes.remove(outcome);
    }

    public void addOutcome(IntelOutcome outcome) {
        if (outcomes == null) {
            outcomes = new ArrayList<>();
        }
        this.outcomes.add(outcome);
    }

    public void removeOutcomes(ArrayList<IntelOutcome> outcomes) {
        if (this.outcomes == null) {
            return;
        }
        this.outcomes.removeAll(outcomes);
    }

    public void addOutcomes(ArrayList<IntelOutcome> outcomes) {
        if (this.outcomes == null) {
            this.outcomes = new ArrayList<>();
        }
        this.outcomes.addAll(outcomes);
    }

    public EventState getState() {
        return state;
    }

    public void setState(EventState state) {
        this.state = state;
    }

    public String update(LocalDate date) {
        StringBuilder builder = new StringBuilder();

        // Update state if necessary.
        EventState newState = switch (state) {
            // Not-started events start on or after their start date
            case NOT_STARTED -> (date.equals(startDate) || date.isAfter(startDate)) ? EventState.STARTED : EventState.NOT_STARTED;
            // Incomplete events expire after their end date
            case PARTIALLY_COMPLETED, STARTED -> (date.isAfter(endDate)) ? EventState.EXPIRED : state;
            // Other state transitions are handled by defined outcomes
            case EXPIRED, COMPLETED, SUCCEEDED, FAILED, DRAW -> state;
        };

        // Print if an event has started
        if (state == EventState.NOT_STARTED && newState == EventState.STARTED) {
            builder.append(String.format(resources.getString("event.started.text"), title))
                  .append(System.lineSeparator());
        }

        // Print if an event has expired
        if (state != EventState.EXPIRED && newState == EventState.EXPIRED) {
            builder.append(String.format(resources.getString("event.expired.text"), title))
                  .append(System.lineSeparator());
        }

        // Apply new state
        state = newState;

        // Check for Started -> Partially Complete transition using testFunctions

        // See if we can partially or fully complete this event now.
        // Events without any testFunctions complete as soon as they start and are never expired.
        if (testFunctions.isEmpty()) {
            if (state == EventState.STARTED) {
                state = EventState.COMPLETED;
                builder.append(String.format(resources.getString("event.completed.text"), title))
                      .append(System.lineSeparator());
            }
        } else {
            // Count the number of passing testFunctions
            int completedTests = (int) testFunctions.stream().filter(Supplier::get).count();

            if (completedTests > 0) {
                // If all are passing and the event has not expired, mark it completed
                if (completedTests == testFunctions.size() && state != EventState.EXPIRED) {
                    state = EventState.COMPLETED;
                    builder.append(String.format(resources.getString("event.completed.text"), title))
                          .append(System.lineSeparator());
                } else {
                    // If some are passing, we are _partially_ completed
                    // Only check for STARTED; can't go back from PARTIALLY_COMPLETED, only forward.
                    if (state == EventState.STARTED) {
                        state = EventState.PARTIALLY_COMPLETED;
                        builder.append(String.format(resources.getString("event.partially.text"), title))
                              .append(System.lineSeparator());
                    }
                }
            }
        }

        // Now evaluate the IntelOutcomes.
        // If order is important, the EspionageFactory is responsible for ensuring correct order.
        for (IntelOutcome outcome : outcomes) {
            if (outcome.checkAchieved()) {
                builder.append(String.format(resources.getString("event.outcome.text"), title, outcome.getTitle()))
                      .append(System.lineSeparator());
                outcome.apply();
            }
        }

        return builder.toString();
    }

    public static IntelEvent generateInstanceFromXML(Node node, Campaign campaign, Version version) {
        IntelEvent retVal = null;
        NamedNodeMap attrs = node.getAttributes();
        Node classNameNode = attrs.getNamedItem("type");
        String className = classNameNode.getTextContent();

        try {
            retVal = (IntelEvent) Class.forName(className).getDeclaredConstructor().newInstance();
            retVal.loadFieldsFromXmlNode(campaign, version, node);

        } catch (Exception ex) {
            LOGGER.error("", ex);
        }

        return retVal;
    }

    public void writeToXML(Campaign campaign, final PrintWriter pw, int indent) {
        indent = writeToXMLBegin(campaign, pw, indent);
        writeToXMLEnd(pw, indent);
    }

    protected int writeToXMLBegin(Campaign campaign, final PrintWriter pw, int indent) {
        MHQXMLUtility.writeSimpleXMLOpenTag(pw, indent++, "intelEvent", "eventId", eventId, "type", getClass());
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "eventState", state.toString());
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "title", title);
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "description", description);
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "location", locationParts);
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "startDate", startDate.toString());
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "endDate", endDate.toString());

        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "participantIds", participantIds);
        MHQXMLUtility.writeSimpleXMLTag(pw, indent, "itemIds", itemIds);

        MHQXMLUtility.writeSimpleXMLOpenTag(pw, indent++, "intelEventPrerequisites", "count", prerequisites.size());
        for (IntelEventPrerequisite prerequisite : prerequisites) {
            prerequisite.writeToXML(campaign, pw, indent);
        }
        MHQXMLUtility.writeSimpleXMLCloseTag(pw, --indent, "intelEventPrerequisites");

        // ISerializableSupplier and ISerializableRunner get passed to the CDATA writer to become base64 encoded
        MHQXMLUtility.writeSimpleXMLOpenTag(pw, indent++, "testFunctions", "count", testFunctions.size());
        for (ISerializableSupplier<Boolean> testFunction : testFunctions) {
            MHQXMLUtility.writeSerialCDATA(pw, indent, "testFunction", testFunction);
        }
        MHQXMLUtility.writeSimpleXMLCloseTag(pw, --indent, "testFunctions");

        MHQXMLUtility.writeSimpleXMLOpenTag(pw, indent++, "outcomes", "count", outcomes.size());
        for (IntelOutcome outcome : outcomes) {
            outcome.writeToXML(campaign, pw, indent);
        }
        MHQXMLUtility.writeSimpleXMLCloseTag(pw, --indent, "outcomes");
        return indent;
    }

    protected void writeToXMLEnd(final PrintWriter pw, int indent) {
        MHQXMLUtility.writeSimpleXMLCloseTag(pw, --indent, "intelEvent");
    }

    public void loadFieldsFromXmlNode(Campaign campaign, Version version, Node node) throws ParseException {
        // Level is stored as an attribute of the node
        try {
            eventId = Integer.parseInt(node.getAttributes().getNamedItem("eventId").getNodeValue());
        } catch (Exception e) {
            LOGGER.error("", e);
        }

        NodeList childNodes = node.getChildNodes();

        for (int x = 0; x < childNodes.getLength(); x++) {
            Node item = childNodes.item(x);
            try {
                if (item.getNodeName().equalsIgnoreCase("eventState")) {
                    state = EventState.valueOf(item.getTextContent());
                } else if (item.getNodeName().equalsIgnoreCase("title")) {
                    title = item.getTextContent();
                } else if (item.getNodeName().equalsIgnoreCase("description")) {
                    description = item.getTextContent();
                } else if (item.getNodeName().equalsIgnoreCase("location")) {
                    locationParts =
                          new ArrayList<String>(List.of(
                                MHQXMLUtility.parseStringArray(item.getTextContent()))
                          );
                } else if (item.getNodeName().equalsIgnoreCase("startDate")) {
                    startDate = LocalDate.parse(item.getTextContent());
                } else if (item.getNodeName().equalsIgnoreCase("endDate")) {
                    endDate = LocalDate.parse(item.getTextContent());
                } else if (item.getNodeName().equalsIgnoreCase("participantIds")) {
                    int[] idArray  = MHQXMLUtility.parseIntArray(item.getTextContent());
                    participantIds = new ArrayList(List.of(idArray));
                } else if (item.getNodeName().equalsIgnoreCase("itemIds")) {
                    int[] idArray  = MHQXMLUtility.parseIntArray(item.getTextContent());
                    itemIds = new ArrayList(List.of(idArray));
                } else if (item.getNodeName().equalsIgnoreCase("intelEventPrerequisites")) {
                    NodeList prerequisiteNodes = item.getChildNodes();
                    for (int y = 0; y < prerequisiteNodes.getLength(); y++) {
                        Node prereqNode = prerequisiteNodes.item(y);
                        if (prereqNode.getNodeName().equalsIgnoreCase("intelEventPrerequisite")) {
                            IntelEventPrerequisite prerequisite =
                                  IntelEventPrerequisite.generateInstanceFromXML(prerequisiteNodes.item(y),
                                        campaign,
                                        version);
                            prerequisites.add(prerequisite);
                        }
                    }
                } else if (item.getNodeName().equalsIgnoreCase("testFunctions")) {
                    NodeList testFunctionNodes = item.getChildNodes();
                    for (int y = 0; y < testFunctionNodes.getLength(); y++) {
                        Node testFuncNode = testFunctionNodes.item(y);
                        if (testFuncNode.getNodeName().equalsIgnoreCase("testFunction")) {
                            ISerializableSupplier<Boolean> function =
                                  (ISerializableSupplier<Boolean>) MHQXMLUtility.parseSerialCDATA(
                                        testFunctionNodes.item(y).getTextContent());
                            testFunctions.add(function);
                        }
                    }
                } else if (item.getNodeName().equalsIgnoreCase("outcomes")) {
                    NodeList outcomeNodes = item.getChildNodes();
                    for (int y = 0; y < outcomeNodes.getLength(); y++) {
                        Node outcomeNode = outcomeNodes.item(y);
                        if (outcomeNode.getNodeName().equalsIgnoreCase("intelOutcome")) {
                            IntelOutcome outcome = IntelOutcome.generateInstanceFromXML(outcomeNodes.item(y),
                                  campaign,
                                  version);
                            outcomes.add(outcome);
                        }
                    }
                }
            } catch (Exception e) {
                LOGGER.error("", e);
            }
        }
    }
}
